services:
  backend:
    image: ghcr.io/freeuni-oop/gitbounty-backend:main
    container_name: gitbounty-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - gitbounty-repositories:/app/repositories
    environment:
      - SPRING_APPLICATION_NAME=Backend
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_FLYWAY_USER=${FLYWAY_USER}
      - SPRING_FLYWAY_PASSWORD=${FLYWAY_PASSWORD}
      - GIT_REPOSITORIES_ROOT=/app/repositories
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - SWAGGER_ENABLED=${SWAGGER_ENABLED}
      - SWAGGER_OAUTH_CLIENT_ID=${SWAGGER_OAUTH_CLIENT_ID}
    develop:
      watch:
        - path: Backend/src
          action: rebuild
    networks:
      - gitbounty-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
#
#  mysql:
#    image: mysql:8.0
#    container_name: gitbounty-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: gitbounty
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#      - ./db/init:/docker-entrypoint-initdb.d
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
#      timeout: 10s
#      retries: 10
#      interval: 5s
#    networks:
#      - gitbounty-network

  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
        - gitbounty-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: gitbounty-keycloak
    command: start-dev --import-realm
#    build:
#      context: .
#      dockerfile: ./keycloak/Dockerfile
    environment:
        JAVA_OPTS_APPEND: -Xms256m -Xmx512m
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_FEATURES: hostname:v2
        KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
        KC_HOSTNAME: ${KEYCLOAK_ISSUER_URI}
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    networks:
      - gitbounty-network

  frontend:
    image: ghcr.io/freeuni-oop/gitbounty-frontend:main

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - gitbounty-network


volumes:
  mysql-data:
  gitbounty-repositories:
  keycloak_db_data:
  caddy_config:
  caddy_data:

networks:
  gitbounty-network: