CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP(6) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255),
                       username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE repositories (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              created_at TIMESTAMP(6),
                              updated_at TIMESTAMP(6),
                              description TEXT,
                              name VARCHAR(255) NOT NULL UNIQUE,
                              url VARCHAR(255) NOT NULL
);

CREATE TABLE issues (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        author_id BIGINT NOT NULL,
                        repository_id BIGINT NOT NULL,
                        created_at TIMESTAMP(6),
                        updated_at TIMESTAMP(6),
                        description TEXT,
                        status VARCHAR(255) NOT NULL,
                        title VARCHAR(255) NOT NULL,
                        CONSTRAINT fk_issues_author FOREIGN KEY (author_id) REFERENCES users(id),
                        CONSTRAINT fk_issues_repo FOREIGN KEY (repository_id) REFERENCES repositories(id)
);