CREATE TABLE repositories (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              created_at TIMESTAMP(6),
                              updated_at TIMESTAMP(6),
                              description TEXT,
                              name VARCHAR(255) NOT NULL UNIQUE,
                              url VARCHAR(255) NOT NULL
);