spring.application.name=Backend
server.port=8081
spring.docker.compose.enabled=false

# Default profile for local development
spring.profiles.active=dev

# JPA / Hibernate Configuration
spring.jpa.properties.hibernate.format_sql=true


