server.port=${SERVER_PORT:8081}
spring.docker.compose.enabled=false

# App Paths
git.repositories-root=${GIT_REPOSITORIES_ROOT:repositories}

# Proxy Support
server.forward-headers-strategy=FRAMEWORK

springdoc.swagger-ui.url=/v3/api-docs
# This allows Swagger to know the base URL of your API
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
