name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Build and Push"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    # Only run if the Build workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Copy the compose file to the server
      - name: Copy docker compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "compose.yaml,Caddyfile"
          target: "/home/gitbounty"

      # 2. Setup Server Environment
      - name: Prepare Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/gitbounty
            echo -e "${{ secrets.ENV_FILE_CONTENT }}" > /home/gitbounty/.env
            chmod 600 /home/gitbounty/.env
      - name: Deploy to Remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Navigate to the directory
            cd /home/gitbounty
            
            # 2. Authenticate the server's Docker daemon to GHCR
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ secrets.GH_USERNAME }}" --password-stdin
            
            # 3. Pull and update
            docker compose pull
            docker compose up -d
            
            # 4. Cleanup
            docker image prune -f